### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(DataViewerContent)
add_subdirectory(DataViewer)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    DataViewerContentplugin
    DataViewerplugin)